# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('special', '0002_delete_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('ticker_symbol', models.CharField(max_length=20)),
                ('stock_data', jsonfield.fields.JSONField()),
            ],
        ),
    ]
