# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 07:01
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0003_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='stock_data',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
