# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 07:02
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0004_auto_20160529_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='stock_data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
