# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0008_industry_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='special.Industry'),
        ),
        migrations.AddField(
            model_name='company',
            name='sector_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='special.Sector'),
        ),
    ]
