# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0009_auto_20160529_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sector',
        ),
    ]
