# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0010_auto_20160529_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('price_range', models.FloatField()),
                ('date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='special.Company')),
            ],
        ),
    ]
