# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0011_daily_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_change',
            name='company',
        ),
        migrations.DeleteModel(
            name='Daily_Change',
        ),
    ]
