# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0012_auto_20160530_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='ticker_symbol',
            new_name='symbol',
        ),
    ]
