# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0013_auto_20160530_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='industry_id',
            new_name='industry',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='sector_id',
            new_name='sector',
        ),
    ]
