# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 23:16
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0014_auto_20160530_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
